[theme]
primaryColor = "#1A73E8"
backgroundColor = "#FFFBFE"
secondaryBackgroundColor = "#F7F2FA"
textColor = "#1C1B1F"
font = "sans serif"

[server]
enableStaticServing = true
maxUploadSize = 100

[browser]
gatherUsageStats = false
