[theme]
base = "dark"
primaryColor = "#3DDC97"
backgroundColor = "#070908"
secondaryBackgroundColor = "#101412"
textColor = "#F4F7F5"
font = "sans serif"

[server]
enableStaticServing = true
maxUploadSize = 100

[browser]
gatherUsageStats = false
